package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.buildings;

public interface buildingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(buildings row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(buildings row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    buildings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKeySelective(buildings row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buildings
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKey(buildings row);
}