package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.businessPrice;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface businessPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(businessPrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(businessPrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    businessPrice selectByPrimaryKey(Integer id);

    businessPrice selectByStations(String startStation, String endStation); // 这里可能也要改，希望输出的是数值
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKeySelective(businessPrice row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKey(businessPrice row);
}