package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.busStop;

public interface busStopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_stop
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_stop
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(busStop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_stop
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(busStop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_stop
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    busStop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_stop
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKeySelective(busStop row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_stop
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKey(busStop row);
}