package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.cardRide;

public interface cardRideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_ride
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_ride
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(cardRide row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_ride
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(cardRide row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_ride
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    cardRide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_ride
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKeySelective(cardRide row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_ride
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKey(cardRide row);
}