package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.lineDetail;

public interface lineDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_detail
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(lineDetail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_detail
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(lineDetail row);
}