package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.price;

public interface priceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(price row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(price row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    price selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKeySelective(price row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKey(price row);
}