package cs307.cs30724springproject2.mapper;

import cs307.cs30724springproject2.entity.station;

public interface stationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insert(station row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int insertSelective(station row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    station selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKeySelective(station row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    int updateByPrimaryKey(station row);
}