package cs307.cs30724springproject2.entity;

public class buildings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.exit_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer exitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buildings.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.id
     *
     * @return the value of buildings.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.id
     *
     * @param id the value for buildings.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.exit_id
     *
     * @return the value of buildings.exit_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getExitId() {
        return exitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.exit_id
     *
     * @param exitId the value for buildings.exit_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setExitId(Integer exitId) {
        this.exitId = exitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buildings.name
     *
     * @return the value of buildings.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buildings.name
     *
     * @param name the value for buildings.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}