package cs307.cs30724springproject2.entity;

public class businessPrice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.start_station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String startStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.end_station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String endStation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column price.price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer price;

    public businessPrice( Integer id, String startStation, String endStation, Integer price ) {
        this.id = id;
        this.startStation = startStation;
        this.endStation = endStation;
        this.price = price;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.id
     *
     * @return the value of price.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.id
     *
     * @param id the value for price.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.start_station
     *
     * @return the value of price.start_station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getStartStation() {
        return startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.start_station
     *
     * @param startStation the value for price.start_station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setStartStation(String startStation) {
        this.startStation = startStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.end_station
     *
     * @return the value of price.end_station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getEndStation() {
        return endStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.end_station
     *
     * @param endStation the value for price.end_station
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setEndStation(String endStation) {
        this.endStation = endStation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column price.price
     *
     * @return the value of price.price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column price.price
     *
     * @param price the value for price.price
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}