package cs307.cs30724springproject2.entity;

public class busLineKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_line.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_line.bus_stop_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer busStopId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_line.name
     *
     * @return the value of bus_line.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_line.name
     *
     * @param name the value for bus_line.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_line.bus_stop_id
     *
     * @return the value of bus_line.bus_stop_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getBusStopId() {
        return busStopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_line.bus_stop_id
     *
     * @param busStopId the value for bus_line.bus_stop_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setBusStopId(Integer busStopId) {
        this.busStopId = busStopId;
    }
}