package cs307.cs30724springproject2.entity;

public class exit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exit.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exit.station_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exit.number
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exit.id
     *
     * @return the value of exit.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exit.id
     *
     * @param id the value for exit.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exit.station_id
     *
     * @return the value of exit.station_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exit.station_id
     *
     * @param stationId the value for exit.station_id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exit.number
     *
     * @return the value of exit.number
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exit.number
     *
     * @param number the value for exit.number
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setNumber(String number) {
        this.number = number;
    }
}