package cs307.cs30724springproject2.entity;

import java.util.Date;

public class line {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.start_time
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.end_time
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.intro
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.mileage
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Double mileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.color
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.first_opening
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Date firstOpening;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line.url
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.name
     *
     * @return the value of line.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.name
     *
     * @param name the value for line.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.start_time
     *
     * @return the value of line.start_time
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.start_time
     *
     * @param startTime the value for line.start_time
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.end_time
     *
     * @return the value of line.end_time
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.end_time
     *
     * @param endTime the value for line.end_time
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.intro
     *
     * @return the value of line.intro
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.intro
     *
     * @param intro the value for line.intro
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.mileage
     *
     * @return the value of line.mileage
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Double getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.mileage
     *
     * @param mileage the value for line.mileage
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setMileage(Double mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.color
     *
     * @return the value of line.color
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.color
     *
     * @param color the value for line.color
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.first_opening
     *
     * @return the value of line.first_opening
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Date getFirstOpening() {
        return firstOpening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.first_opening
     *
     * @param firstOpening the value for line.first_opening
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setFirstOpening(Date firstOpening) {
        this.firstOpening = firstOpening;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line.url
     *
     * @return the value of line.url
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line.url
     *
     * @param url the value for line.url
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setUrl(String url) {
        this.url = url;
    }
}