package cs307.cs30724springproject2.entity;

public class lineDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_detail.line_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String lineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_detail.station_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String stationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_detail.line_name
     *
     * @return the value of line_detail.line_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_detail.line_name
     *
     * @param lineName the value for line_detail.line_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setLineName(String lineName) {
        this.lineName = lineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_detail.station_name
     *
     * @return the value of line_detail.station_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getStationName() {
        return stationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_detail.station_name
     *
     * @param stationName the value for line_detail.station_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setStationName(String stationName) {
        this.stationName = stationName;
    }
}