package cs307.cs30724springproject2.entity;

public class passenger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.phone_number
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Long phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.gender
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passenger.district
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String district;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.id
     *
     * @return the value of passenger.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.id
     *
     * @param id the value for passenger.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.name
     *
     * @return the value of passenger.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.name
     *
     * @param name the value for passenger.name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.phone_number
     *
     * @return the value of passenger.phone_number
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Long getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.phone_number
     *
     * @param phoneNumber the value for passenger.phone_number
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.gender
     *
     * @return the value of passenger.gender
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.gender
     *
     * @param gender the value for passenger.gender
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passenger.district
     *
     * @return the value of passenger.district
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passenger.district
     *
     * @param district the value for passenger.district
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setDistrict(String district) {
        this.district = district;
    }
}