package cs307.cs30724springproject2.entity;

public class station {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.district
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.english_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.chinese_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String chineseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.intro
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    private String intro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.id
     *
     * @return the value of station.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.id
     *
     * @param id the value for station.id
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.district
     *
     * @return the value of station.district
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.district
     *
     * @param district the value for station.district
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.english_name
     *
     * @return the value of station.english_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.english_name
     *
     * @param englishName the value for station.english_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.chinese_name
     *
     * @return the value of station.chinese_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getChineseName() {
        return chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.chinese_name
     *
     * @param chineseName the value for station.chinese_name
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.intro
     *
     * @return the value of station.intro
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.intro
     *
     * @param intro the value for station.intro
     *
     * @mbg.generated Thu May 16 01:10:29 CST 2024
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }
}